<a href="https://colab.research.google.com/github/AnnisaFarikha/Kecerdasan-Buatan/blob/main/Jobsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tipe Data Python

In [ ]:
# A. Cek Tipe Data
var = 123
print(type(var))

# B. Tipe Data String
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

# C. Tipe Data Numerik
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)
sum = var1 + var2
print(sum)
var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

# D. Tipe Data Boolean
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

# E. Tipe Data List
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))

<class 'int'>
<class 'str'>
<class 'float'>
345.0
379.5
34
12
False
False
True
True
['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


#Operasi Matematika Menggunakan Python

In [ ]:
# A. Mendapatkan nilai minimum dan maksimum
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

# B. Mendapatkan nilai absolut
x = abs(-7.25)
print(x)

# C. Mendapatkan nilai pangkat
import math
x = math.pow(4, 3)
print(x)

# D. Mendapatkan nilai akar
import math
x = math.sqrt(64)
print(x)

# E. Mendapatkan nilai pembulatan
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

# F. Mendapatkan nilai konstanta (PI)
import math
x = math.pi
print(x)

5
18
7.25
64.0
8.0
2
1
3.141592653589793


#Menggunakan Fungsi MATH

In [ ]:
import math

print("math.sin(30) =", math.sin(30))
print("math.cos(30) =", math.cos(30))
print("math.tan(30) =", math.tan(30))

print("math.log(10) =", math.log(10))
print("math.log10(100) =", math.log10(100))

print("math.degrees(3.14) =", math.degrees(3.14))

print("math.dist([2,3], [5,7]) =", math.dist([2,3], [5,7]))

print("math.factorial(5) =", math.factorial(5))

print("math.fmod(10,3) =", math.fmod(10,3))

print("math.isnan(5.6) =", math.isnan(5.6))

print("math.gamma(5) =", math.gamma(5))

print("math.perm(5,2) =", math.perm(5,2))

math.sin(30) = -0.9880316240928618
math.cos(30) = 0.15425144988758405
math.tan(30) = -6.405331196646276
math.log(10) = 2.302585092994046
math.log10(100) = 2.0
math.degrees(3.14) = 179.9087476710785
math.dist([2,3], [5,7]) = 5.0
math.factorial(5) = 120
math.fmod(10,3) = 1.0
math.isnan(5.6) = False
math.gamma(5) = 24.0
math.perm(5,2) = 20


#Operasi Matriks dan Vektor dengan Python

In [ ]:
# A. Membuat matriks di pyhon
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
print(hasil)

# B. Melakukan operasi dot product
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

# C. Melakukan operasi cross product
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.cross(A, B)
print(hasil)

[[110  90  40]
 [ 60  50  40]]
2025
[-305 -110  350]


#Tugas 1: Perkalian

In [ ]:
import numpy as np

A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])

hasil1 = np.dot(A, B)   # A x B
hasil2 = np.dot(B, C)   # B . C

print("A x B =")
print(hasil1)

print("B . C =")
print(hasil2)

A x B =
[[7 2]
 [4 2]]
B . C =
[[ 0  2  3]
 [-3  1  3]]


#Tugas 2: Faktorial

In [ ]:
import math

a = math.factorial(6)                       # 6!
b = math.factorial(8) / math.factorial(5)   # 8! / 5!

print("6! =", a)
print("8! / 5! =", b)

6! = 720
8! / 5! = 336.0


#Tugas 3: Vektor

In [ ]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Panjang vektor
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot = np.dot(A, B)       # Dot Product
cross = np.cross(A, B)   # Cross Product

print("Panjang Vektor A =", panjang_A)
print("Panjang Vektor B =", panjang_B)

print("A . B =", dot)

print("A x B =")
print(cross)

Panjang Vektor A = 9.1104335791443
Panjang Vektor B = 12.409673645990857
A . B = 58
A x B =
[ 24  79 -51]
